export const aeraOfExpertise = [
    { value: 'computer_science', label: 'Computer Science' },
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'physics', label: 'Physics' },
    { value: 'chemistry', label: 'Chemistry' },
    { value: 'biology', label: 'Biology' },
    { value: 'engineering', label: 'Engineering' },
    { value: 'medicine', label: 'Medicine' },
    { value: 'law', label: 'Law' },
    { value: 'education', label: 'Education' },
    { value: 'psychology', label: 'Psychology' },
    { value: 'sociology', label: 'Sociology' },
    { value: 'political_science', label: 'Political Science' },
    { value: 'economics', label: 'Economics' },
    { value: 'history', label: 'History' },
    { value: 'literature', label: 'Literature' },
    { value: 'art', label: 'Art' },
    { value: 'music', label: 'Music' },
    { value: 'dance', label: 'Dance' },
    { value: 'theatre', label: 'Theatre' },
    { value: 'agriculture', label: 'Agriculture' },
    { value: 'anthropology', label: 'Anthropology' },
    { value: 'archaeology', label: 'Archaeology' },
    { value: 'architecture', label: 'Architecture' },
    { value: 'business', label: 'Business' },
    { value: 'communication', label: 'Communication' },
    { value: 'computer_engineering', label: 'Computer Engineering' },
    { value: 'environmental_science', label: 'Environmental Science' },
    { value: 'geography', label: 'Geography' },
    { value: 'geology', label: 'Geology' },
    { value: 'information_technology', label: 'Information Technology' },
    { value: 'journalism', label: 'Journalism' },
    { value: 'linguistics', label: 'Linguistics' },
    { value: 'marketing', label: 'Marketing' },
    { value: 'philosophy', label: 'Philosophy' },
    { value: 'physical_therapy', label: 'Physical Therapy' },
    { value: 'public_health', label: 'Public Health' },
    { value: 'public_policy', label: 'Public Policy' },
    { value: 'religious_studies', label: 'Religious Studies' },
    { value: 'speech_therapy', label: 'Speech Therapy' },
    { value: 'data_science', label: 'Data Science' },
    { value: 'artificial_intelligence', label: 'Artificial Intelligence' },
    { value: 'machine_learning', label: 'Machine Learning' },
    { value: 'web_development', label: 'Web Development' },
    { value: 'mobile_development', label: 'Mobile Development' },

]